use_frameworks!
platform:ios,'9.0'
inhibit_all_warnings!

target 'TokenHybrid' do
    pod 'YogaKit'
    pod 'SDWebImage'
    pod 'MJRefresh'
    pod 'UITableView+FDTemplateLayoutCell'
    pod 'TokenNetworking'
end

